-- Generated by scripts/migrate-diff.mjs — do not edit by hand

DROP TABLE poll_runs; -- due to schema mismatch
CREATE TABLE poll_runs (
  id TEXT PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'partial', 'failed')),
  repos_checked INTEGER NOT NULL DEFAULT 0,
  tickets_created INTEGER NOT NULL DEFAULT 0,
  tickets_superseded INTEGER NOT NULL DEFAULT 0,
  errors_json TEXT NOT NULL DEFAULT '[]'
);
CREATE INDEX idx_poll_runs_started ON poll_runs (started_at);
