-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=add_content_templates_to_ticket_projects

PRAGMA foreign_keys = ON;

ALTER TABLE "ticket_projects" ADD COLUMN "content_templates" TEXT NOT NULL DEFAULT '{"title":"","description":"","supersedeComment":""}' CHECK (json_valid(content_templates));
