-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=add_include_prereleases_to_monitored_repos

PRAGMA foreign_keys = ON;

ALTER TABLE "monitored_repos" ADD COLUMN "include_prereleases" INTEGER NOT NULL DEFAULT 0 CHECK (include_prereleases IN (0, 1));
