-- Generated by scripts/migrate-diff.mjs — do not edit by hand

PRAGMA foreign_keys=OFF;

CREATE TABLE "monitored_repos_new" (
  id TEXT PRIMARY KEY,
  source_kind TEXT NOT NULL CHECK (
    source_kind IN ('github', 'gitlab', 'gitea', 'forgejo', 'codeberg')
  ),
  project_path TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  source_integration_id TEXT REFERENCES integrations(id),
  ticket_project_id TEXT NOT NULL REFERENCES ticket_projects(id) ON DELETE RESTRICT,
  open_ticket_external_id TEXT,
  open_ticket_tag TEXT,
  last_known_tag TEXT,
  last_polled_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (source_kind, project_path)
);

INSERT INTO "monitored_repos_new" ("id", "source_kind", "project_path", "enabled", "source_integration_id", "ticket_project_id", "open_ticket_external_id", "open_ticket_tag", "last_known_tag", "last_polled_at", "last_error", "created_at", "updated_at") SELECT "id", "source_kind", "project_path", "enabled", "source_integration_id", "ticket_project_id", "open_ticket_external_id", "open_ticket_tag", "last_known_tag", "last_polled_at", "last_error", "created_at", "updated_at" FROM "monitored_repos";

DROP TABLE "monitored_repos";

ALTER TABLE "monitored_repos_new" RENAME TO "monitored_repos";

CREATE INDEX idx_monitored_repos_enabled ON monitored_repos (enabled);

CREATE INDEX idx_monitored_repos_source ON monitored_repos (source_kind);

CREATE INDEX idx_monitored_repos_ticket_project ON monitored_repos (ticket_project_id);

PRAGMA foreign_keys=ON;
