-- Generated by scripts/migrate-diff.mjs — do not edit by hand

DROP TABLE app_settings;
DROP TABLE integrations;
DROP TABLE monitored_repo_notifications;
DROP TABLE monitored_repos;
DROP TABLE notification_targets;
DROP TABLE poll_run_events;
DROP TABLE poll_runs;
DROP TABLE sessions;
DROP TABLE ticket_projects;
DROP TABLE users;
