-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=poll_run_trigger_source

PRAGMA foreign_keys = ON;

DROP TABLE poll_runs; -- due to schema mismatch
CREATE TABLE poll_runs (
  id TEXT PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'partial', 'failed')),
  trigger_source TEXT NOT NULL DEFAULT 'scheduled' CHECK (trigger_source IN ('manual', 'scheduled')),
  repos_checked INTEGER NOT NULL DEFAULT 0,
  tickets_created INTEGER NOT NULL DEFAULT 0,
  tickets_superseded INTEGER NOT NULL DEFAULT 0,
  errors_json TEXT NOT NULL DEFAULT '[]'
);
CREATE INDEX idx_poll_runs_started ON poll_runs (started_at);
