-- Generated by scripts/migrate-diff.mjs — do not edit by hand

PRAGMA foreign_keys=OFF;

CREATE TABLE "ticket_projects_new" (
  id TEXT PRIMARY KEY,
  integration_id TEXT NOT NULL REFERENCES integrations(id) ON DELETE RESTRICT,
  external_project_id TEXT NOT NULL,
  name TEXT NOT NULL,
  create_config TEXT NOT NULL,
  status_mapping TEXT NOT NULL,
  on_open_ticket_policy TEXT NOT NULL DEFAULT 'supersede' CHECK (
    on_open_ticket_policy IN ('supersede', 'merge', 'skip_if_open')
  ),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (integration_id, external_project_id),
  CHECK (json_valid(create_config) AND json_valid(status_mapping))
);

INSERT INTO "ticket_projects_new" ("id", "integration_id", "external_project_id", "name", "create_config", "status_mapping", "on_open_ticket_policy", "created_at", "updated_at") SELECT "id", "integration_id", "external_project_id", "name", "create_config", "status_mapping", "on_open_ticket_policy", "created_at", "updated_at" FROM "ticket_projects";

DROP TABLE "ticket_projects";

ALTER TABLE "ticket_projects_new" RENAME TO "ticket_projects";

CREATE INDEX idx_ticket_projects_integration ON ticket_projects (integration_id);

PRAGMA foreign_keys=ON;
