-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- data-safe-rebuild: table rebuild preserves app_settings rows

DROP TABLE auth_tokens;
DROP INDEX IF EXISTS idx_sessions_user_id;
ALTER TABLE sessions DROP COLUMN user_id;

PRAGMA foreign_keys=OFF;
CREATE TABLE app_settings_new (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  poll_interval_minutes INTEGER NOT NULL DEFAULT 360 CHECK (poll_interval_minutes >= 5),
  updated_at TEXT NOT NULL
);
INSERT INTO app_settings_new (id, poll_interval_minutes, updated_at)
SELECT id, poll_interval_minutes, updated_at FROM app_settings;
DROP TABLE app_settings;
ALTER TABLE app_settings_new RENAME TO app_settings;
PRAGMA foreign_keys=ON;
