-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=monitored_repos_last_release_published_at

PRAGMA foreign_keys = ON;

ALTER TABLE "monitored_repos" ADD COLUMN "last_release_published_at" TEXT;
