-- Generated by scripts/migrate-diff.mjs — do not edit by hand

DROP TABLE app_settings; -- due to schema mismatch
CREATE TABLE app_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  poll_interval_minutes INTEGER NOT NULL DEFAULT 360 CHECK (poll_interval_minutes >= 5),
  updated_at TEXT NOT NULL
);
DROP TABLE auth_tokens;
DROP TABLE sessions; -- due to schema mismatch
CREATE TABLE sessions (
  token TEXT PRIMARY KEY,
  data BLOB NOT NULL,
  expiry REAL NOT NULL
);
CREATE INDEX idx_sessions_expiry ON sessions (expiry);
