-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=poll_run_trigger_source
-- data-safe: ADD COLUMN preserves poll_runs and poll_run_events rows (modernc FK always on)

PRAGMA foreign_keys = ON;

ALTER TABLE poll_runs ADD COLUMN trigger_source TEXT NOT NULL DEFAULT 'scheduled' CHECK (trigger_source IN ('manual', 'scheduled'));
