-- Generated by scripts/migrate-diff.mjs — do not edit by hand
-- Re-generate: make migrate-diff name=rename_phasical_to_kaneo

PRAGMA foreign_keys = ON;

PRAGMA foreign_keys=OFF;

CREATE TABLE "integrations_new" (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (
    kind IN ('github', 'gitlab', 'gitea', 'forgejo', 'codeberg', 'kaneo', 'jira', 'linear')
  ),
  name TEXT NOT NULL,
  base_url TEXT,
  encrypted_payload TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (
    (kind = 'github' AND base_url IS NULL)
    OR (kind = 'gitlab' AND base_url IS NOT NULL)
    OR (kind = 'gitea' AND base_url IS NOT NULL)
    OR (kind = 'forgejo' AND base_url IS NOT NULL)
    OR (kind = 'codeberg' AND base_url IS NULL)
    OR (kind = 'kaneo' AND base_url IS NOT NULL)
    OR (kind = 'jira' AND base_url IS NOT NULL)
    OR (kind = 'linear' AND base_url IS NULL)
  )
);

INSERT INTO "integrations_new" ("id", "kind", "name", "base_url", "encrypted_payload", "created_at", "updated_at") SELECT "id", "kind", "name", "base_url", "encrypted_payload", "created_at", "updated_at" FROM "integrations";

DROP TABLE "integrations";

ALTER TABLE "integrations_new" RENAME TO "integrations";

CREATE INDEX idx_integrations_kind ON integrations (kind);

CREATE TEMP TABLE "integrations_fk_guard" (violations INTEGER NOT NULL CHECK (violations = 0));

INSERT INTO "integrations_fk_guard" (violations) SELECT COUNT(*) FROM pragma_foreign_key_check;

DROP TABLE "integrations_fk_guard";

PRAGMA foreign_keys=ON;
