// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package db

import (
	"context"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT
  id,
  poll_interval_minutes,
  updated_at
FROM app_settings
WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(&i.ID, &i.PollIntervalMinutes, &i.UpdatedAt)
	return i, err
}

const updatePollInterval = `-- name: UpdatePollInterval :one
UPDATE app_settings
SET
  poll_interval_minutes = ?,
  updated_at = ?
WHERE id = 1
RETURNING id, poll_interval_minutes, updated_at
`

type UpdatePollIntervalParams struct {
	PollIntervalMinutes int64  `json:"poll_interval_minutes"`
	UpdatedAt           string `json:"updated_at"`
}

func (q *Queries) UpdatePollInterval(ctx context.Context, arg UpdatePollIntervalParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updatePollInterval, arg.PollIntervalMinutes, arg.UpdatedAt)
	var i AppSetting
	err := row.Scan(&i.ID, &i.PollIntervalMinutes, &i.UpdatedAt)
	return i, err
}
