// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package db

import (
	"context"
)

const ensureAppSettings = `-- name: EnsureAppSettings :exec
INSERT OR IGNORE INTO app_settings (
  id,
  poll_interval_minutes,
  invite_token_expiry_hours,
  password_reset_token_expiry_minutes,
  updated_at
)
VALUES (1, 360, 168, 60, ?)
`

func (q *Queries) EnsureAppSettings(ctx context.Context, updatedAt string) error {
	_, err := q.db.ExecContext(ctx, ensureAppSettings, updatedAt)
	return err
}

const getAppSettings = `-- name: GetAppSettings :one
SELECT
  id,
  poll_interval_minutes,
  invite_token_expiry_hours,
  password_reset_token_expiry_minutes,
  updated_at
FROM app_settings
WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.PollIntervalMinutes,
		&i.InviteTokenExpiryHours,
		&i.PasswordResetTokenExpiryMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePollInterval = `-- name: UpdatePollInterval :one
UPDATE app_settings
SET
  poll_interval_minutes = ?,
  updated_at = ?
WHERE id = 1
RETURNING
  id,
  poll_interval_minutes,
  invite_token_expiry_hours,
  password_reset_token_expiry_minutes,
  updated_at
`

type UpdatePollIntervalParams struct {
	PollIntervalMinutes int64  `json:"poll_interval_minutes"`
	UpdatedAt           string `json:"updated_at"`
}

func (q *Queries) UpdatePollInterval(ctx context.Context, arg UpdatePollIntervalParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updatePollInterval, arg.PollIntervalMinutes, arg.UpdatedAt)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.PollIntervalMinutes,
		&i.InviteTokenExpiryHours,
		&i.PasswordResetTokenExpiryMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTokenExpirySettings = `-- name: UpdateTokenExpirySettings :one
UPDATE app_settings
SET
  invite_token_expiry_hours = ?,
  password_reset_token_expiry_minutes = ?,
  updated_at = ?
WHERE id = 1
RETURNING
  id,
  poll_interval_minutes,
  invite_token_expiry_hours,
  password_reset_token_expiry_minutes,
  updated_at
`

type UpdateTokenExpirySettingsParams struct {
	InviteTokenExpiryHours          int64  `json:"invite_token_expiry_hours"`
	PasswordResetTokenExpiryMinutes int64  `json:"password_reset_token_expiry_minutes"`
	UpdatedAt                       string `json:"updated_at"`
}

func (q *Queries) UpdateTokenExpirySettings(ctx context.Context, arg UpdateTokenExpirySettingsParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updateTokenExpirySettings, arg.InviteTokenExpiryHours, arg.PasswordResetTokenExpiryMinutes, arg.UpdatedAt)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.PollIntervalMinutes,
		&i.InviteTokenExpiryHours,
		&i.PasswordResetTokenExpiryMinutes,
		&i.UpdatedAt,
	)
	return i, err
}
