// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  used_at,
  created_at
`

type CreateAuthTokenParams struct {
	ID              string         `json:"id"`
	Kind            string         `json:"kind"`
	Email           string         `json:"email"`
	TokenHash       string         `json:"token_hash"`
	NewEmail        sql.NullString `json:"new_email"`
	InvitedByUserID sql.NullString `json:"invited_by_user_id"`
	ExpiresAt       string         `json:"expires_at"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, createAuthToken,
		arg.ID,
		arg.Kind,
		arg.Email,
		arg.TokenHash,
		arg.NewEmail,
		arg.InvitedByUserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.NewEmail,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePendingInvitation = `-- name: DeletePendingInvitation :execrows
DELETE FROM auth_tokens
WHERE id = ?
  AND kind = 'invitation'
  AND used_at IS NULL
`

func (q *Queries) DeletePendingInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  used_at,
  created_at
FROM auth_tokens
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.NewEmail,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthTokenByID = `-- name: GetAuthTokenByID :one
SELECT
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  used_at,
  created_at
FROM auth_tokens
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAuthTokenByID(ctx context.Context, id string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokenByID, id)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.NewEmail,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePasswordResetTokensForEmail = `-- name: InvalidatePasswordResetTokensForEmail :exec
UPDATE auth_tokens
SET used_at = ?
WHERE kind = 'password_reset'
  AND email = ?
  AND used_at IS NULL
`

type InvalidatePasswordResetTokensForEmailParams struct {
	UsedAt sql.NullString `json:"used_at"`
	Email  string         `json:"email"`
}

func (q *Queries) InvalidatePasswordResetTokensForEmail(ctx context.Context, arg InvalidatePasswordResetTokensForEmailParams) error {
	_, err := q.db.ExecContext(ctx, invalidatePasswordResetTokensForEmail, arg.UsedAt, arg.Email)
	return err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT
  id,
  email,
  expires_at,
  created_at,
  invited_by_user_id
FROM auth_tokens
WHERE kind = 'invitation'
  AND used_at IS NULL
  AND expires_at > ?
ORDER BY created_at DESC
`

type ListPendingInvitationsRow struct {
	ID              string         `json:"id"`
	Email           string         `json:"email"`
	ExpiresAt       string         `json:"expires_at"`
	CreatedAt       string         `json:"created_at"`
	InvitedByUserID sql.NullString `json:"invited_by_user_id"`
}

func (q *Queries) ListPendingInvitations(ctx context.Context, expiresAt string) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvitations, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsRow
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InvitedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :one
UPDATE auth_tokens
SET used_at = ?
WHERE id = ?
RETURNING
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  used_at,
  created_at
`

type MarkAuthTokenUsedParams struct {
	UsedAt sql.NullString `json:"used_at"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, arg MarkAuthTokenUsedParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, markAuthTokenUsed, arg.UsedAt, arg.ID)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.NewEmail,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByEmail = `-- name: GetPendingInvitationByEmail :one
SELECT
  id,
  kind,
  email,
  token_hash,
  new_email,
  invited_by_user_id,
  expires_at,
  used_at,
  created_at
FROM auth_tokens
WHERE kind = 'invitation'
  AND email = ?
  AND used_at IS NULL
  AND expires_at > ?
LIMIT 1
`

type GetPendingInvitationByEmailParams struct {
	Email     string `json:"email"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) GetPendingInvitationByEmail(ctx context.Context, arg GetPendingInvitationByEmailParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getPendingInvitationByEmail, arg.Email, arg.ExpiresAt)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.NewEmail,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEmailChangeTokensForEmail = `-- name: InvalidateEmailChangeTokensForEmail :exec
UPDATE auth_tokens
SET used_at = ?
WHERE kind = 'email_change'
  AND email = ?
  AND used_at IS NULL
`

type InvalidateEmailChangeTokensForEmailParams struct {
	UsedAt sql.NullString `json:"used_at"`
	Email  string         `json:"email"`
}

func (q *Queries) InvalidateEmailChangeTokensForEmail(ctx context.Context, arg InvalidateEmailChangeTokensForEmailParams) error {
	_, err := q.db.ExecContext(ctx, invalidateEmailChangeTokensForEmail, arg.UsedAt, arg.Email)
	return err
}
