// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"
	"database/sql"
)

const clearDefaultIntegrationForKind = `-- name: ClearDefaultIntegrationForKind :exec
UPDATE integrations
SET is_default = 0
WHERE kind = ?
  AND is_default = 1
  AND id <> ?
`

type ClearDefaultIntegrationForKindParams struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

func (q *Queries) ClearDefaultIntegrationForKind(ctx context.Context, arg ClearDefaultIntegrationForKindParams) error {
	_, err := q.db.ExecContext(ctx, clearDefaultIntegrationForKind, arg.Kind, arg.ID)
	return err
}

const countIntegrationReferences = `-- name: CountIntegrationReferences :one
SELECT
  (
    SELECT COUNT(*)
    FROM monitored_repos
    WHERE source_integration_id = ?
  ) + (
    SELECT COUNT(*)
    FROM ticket_projects
    WHERE integration_id = ?
  ) AS count
`

type CountIntegrationReferencesParams struct {
	SourceIntegrationID sql.NullString `json:"source_integration_id"`
	IntegrationID       string         `json:"integration_id"`
}

func (q *Queries) CountIntegrationReferences(ctx context.Context, arg CountIntegrationReferencesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIntegrationReferences, arg.SourceIntegrationID, arg.IntegrationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (
  id,
  kind,
  name,
  base_url,
  encrypted_payload,
  created_at,
  updated_at,
  is_default
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, kind, name, base_url, encrypted_payload, created_at, updated_at, is_default
`

type CreateIntegrationParams struct {
	ID               string         `json:"id"`
	Kind             string         `json:"kind"`
	Name             string         `json:"name"`
	BaseUrl          sql.NullString `json:"base_url"`
	EncryptedPayload string         `json:"encrypted_payload"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	IsDefault        int64          `json:"is_default"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRowContext(ctx, createIntegration,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.EncryptedPayload,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDefault,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.EncryptedPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations
WHERE id = ?
`

func (q *Queries) DeleteIntegration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIntegration, id)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT
  id,
  kind,
  name,
  base_url,
  encrypted_payload,
  created_at,
  updated_at,
  is_default
FROM integrations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetIntegration(ctx context.Context, id string) (Integration, error) {
	row := q.db.QueryRowContext(ctx, getIntegration, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.EncryptedPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const listByKind = `-- name: ListByKind :many
SELECT
  id,
  kind,
  name,
  base_url,
  encrypted_payload,
  created_at,
  updated_at,
  is_default
FROM integrations
WHERE kind = ?
ORDER BY name
`

func (q *Queries) ListByKind(ctx context.Context, kind string) ([]Integration, error) {
	rows, err := q.db.QueryContext(ctx, listByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.EncryptedPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT
  id,
  kind,
  name,
  base_url,
  encrypted_payload,
  created_at,
  updated_at,
  is_default
FROM integrations
ORDER BY name
`

func (q *Queries) ListIntegrations(ctx context.Context) ([]Integration, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.EncryptedPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations
SET
  name = ?,
  base_url = ?,
  encrypted_payload = ?,
  is_default = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, kind, name, base_url, encrypted_payload, created_at, updated_at, is_default
`

type UpdateIntegrationParams struct {
	Name             string         `json:"name"`
	BaseUrl          sql.NullString `json:"base_url"`
	EncryptedPayload string         `json:"encrypted_payload"`
	IsDefault        int64          `json:"is_default"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error) {
	row := q.db.QueryRowContext(ctx, updateIntegration,
		arg.Name,
		arg.BaseUrl,
		arg.EncryptedPayload,
		arg.IsDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.EncryptedPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const updateIntegrationName = `-- name: UpdateIntegrationName :one
UPDATE integrations
SET
  name = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, kind, name, base_url, encrypted_payload, created_at, updated_at, is_default
`

type UpdateIntegrationNameParams struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateIntegrationName(ctx context.Context, arg UpdateIntegrationNameParams) (Integration, error) {
	row := q.db.QueryRowContext(ctx, updateIntegrationName, arg.Name, arg.UpdatedAt, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.EncryptedPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}
