// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AppSetting struct {
	ID                              int64  `json:"id"`
	PollIntervalMinutes             int64  `json:"poll_interval_minutes"`
	InviteTokenExpiryHours          int64  `json:"invite_token_expiry_hours"`
	PasswordResetTokenExpiryMinutes int64  `json:"password_reset_token_expiry_minutes"`
	UpdatedAt                       string `json:"updated_at"`
}

type AuthToken struct {
	ID              string         `json:"id"`
	Kind            string         `json:"kind"`
	Email           string         `json:"email"`
	TokenHash       string         `json:"token_hash"`
	NewEmail        sql.NullString `json:"new_email"`
	InvitedByUserID sql.NullString `json:"invited_by_user_id"`
	ExpiresAt       string         `json:"expires_at"`
	UsedAt          sql.NullString `json:"used_at"`
	CreatedAt       string         `json:"created_at"`
}

type Integration struct {
	ID               string         `json:"id"`
	Kind             string         `json:"kind"`
	Name             string         `json:"name"`
	BaseUrl          sql.NullString `json:"base_url"`
	EncryptedPayload string         `json:"encrypted_payload"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type MonitoredRepo struct {
	ID                     string         `json:"id"`
	SourceKind             string         `json:"source_kind"`
	ProjectPath            string         `json:"project_path"`
	Enabled                int64          `json:"enabled"`
	IncludePrereleases     int64          `json:"include_prereleases"`
	SourceIntegrationID    sql.NullString `json:"source_integration_id"`
	TicketProjectID        string         `json:"ticket_project_id"`
	OpenTicketExternalID   sql.NullString `json:"open_ticket_external_id"`
	OpenTicketTag          sql.NullString `json:"open_ticket_tag"`
	LastKnownTag           sql.NullString `json:"last_known_tag"`
	LastReleasePublishedAt sql.NullString `json:"last_release_published_at"`
	LastPolledAt           sql.NullString `json:"last_polled_at"`
	LastError              sql.NullString `json:"last_error"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type MonitoredRepoNotification struct {
	MonitoredRepoID      string `json:"monitored_repo_id"`
	NotificationTargetID string `json:"notification_target_id"`
}

type NotificationTarget struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	ShoutrrrUrlEncrypted string `json:"shoutrrr_url_encrypted"`
	EventsJson           string `json:"events_json"`
	Enabled              int64  `json:"enabled"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type PollRun struct {
	ID                string         `json:"id"`
	StartedAt         string         `json:"started_at"`
	FinishedAt        sql.NullString `json:"finished_at"`
	Status            string         `json:"status"`
	ReposChecked      int64          `json:"repos_checked"`
	TicketsCreated    int64          `json:"tickets_created"`
	TicketsSuperseded int64          `json:"tickets_superseded"`
	ErrorsJson        string         `json:"errors_json"`
	TriggerSource     string         `json:"trigger_source"`
}

type PollRunEvent struct {
	ID              string         `json:"id"`
	PollRunID       string         `json:"poll_run_id"`
	MonitoredRepoID sql.NullString `json:"monitored_repo_id"`
	Action          string         `json:"action"`
	Detail          sql.NullString `json:"detail"`
	CreatedAt       string         `json:"created_at"`
}

type Session struct {
	Token  string         `json:"token"`
	Data   []byte         `json:"data"`
	Expiry float64        `json:"expiry"`
	UserID sql.NullString `json:"user_id"`
}

type TicketProject struct {
	ID                 string `json:"id"`
	IntegrationID      string `json:"integration_id"`
	ExternalProjectID  string `json:"external_project_id"`
	Name               string `json:"name"`
	CreateConfig       string `json:"create_config"`
	StatusMapping      string `json:"status_mapping"`
	ContentTemplates   string `json:"content_templates"`
	OnOpenTicketPolicy string `json:"on_open_ticket_policy"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
