// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitored_repo_notifications.sql

package db

import (
	"context"
)

const deleteMonitoredRepoNotification = `-- name: DeleteMonitoredRepoNotification :exec
DELETE FROM monitored_repo_notifications
WHERE monitored_repo_id = ?
  AND notification_target_id = ?
`

type DeleteMonitoredRepoNotificationParams struct {
	MonitoredRepoID      string `json:"monitored_repo_id"`
	NotificationTargetID string `json:"notification_target_id"`
}

func (q *Queries) DeleteMonitoredRepoNotification(ctx context.Context, arg DeleteMonitoredRepoNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteMonitoredRepoNotification, arg.MonitoredRepoID, arg.NotificationTargetID)
	return err
}

const deleteMonitoredRepoNotificationsByRepo = `-- name: DeleteMonitoredRepoNotificationsByRepo :exec
DELETE FROM monitored_repo_notifications
WHERE monitored_repo_id = ?
`

func (q *Queries) DeleteMonitoredRepoNotificationsByRepo(ctx context.Context, monitoredRepoID string) error {
	_, err := q.db.ExecContext(ctx, deleteMonitoredRepoNotificationsByRepo, monitoredRepoID)
	return err
}

const linkMonitoredRepoNotification = `-- name: LinkMonitoredRepoNotification :exec
INSERT INTO monitored_repo_notifications (
  monitored_repo_id,
  notification_target_id
) VALUES (
  ?,
  ?
)
`

type LinkMonitoredRepoNotificationParams struct {
	MonitoredRepoID      string `json:"monitored_repo_id"`
	NotificationTargetID string `json:"notification_target_id"`
}

func (q *Queries) LinkMonitoredRepoNotification(ctx context.Context, arg LinkMonitoredRepoNotificationParams) error {
	_, err := q.db.ExecContext(ctx, linkMonitoredRepoNotification, arg.MonitoredRepoID, arg.NotificationTargetID)
	return err
}

const listNotificationTargetIDsForRepo = `-- name: ListNotificationTargetIDsForRepo :many
SELECT notification_target_id
FROM monitored_repo_notifications
WHERE monitored_repo_id = ?
ORDER BY notification_target_id
`

func (q *Queries) ListNotificationTargetIDsForRepo(ctx context.Context, monitoredRepoID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationTargetIDsForRepo, monitoredRepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var notification_target_id string
		if err := rows.Scan(&notification_target_id); err != nil {
			return nil, err
		}
		items = append(items, notification_target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
