// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitored_repos.sql

package db

import (
	"context"
	"database/sql"
)

const createMonitoredRepo = `-- name: CreateMonitoredRepo :one
INSERT INTO monitored_repos (
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
`

type CreateMonitoredRepoParams struct {
	ID                   string         `json:"id"`
	SourceKind           string         `json:"source_kind"`
	ProjectPath          string         `json:"project_path"`
	Enabled              int64          `json:"enabled"`
	SourceIntegrationID  sql.NullString `json:"source_integration_id"`
	TicketProjectID      string         `json:"ticket_project_id"`
	OpenTicketExternalID sql.NullString `json:"open_ticket_external_id"`
	OpenTicketTag        sql.NullString `json:"open_ticket_tag"`
	LastKnownTag         sql.NullString `json:"last_known_tag"`
	LastPolledAt         sql.NullString `json:"last_polled_at"`
	LastError            sql.NullString `json:"last_error"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

func (q *Queries) CreateMonitoredRepo(ctx context.Context, arg CreateMonitoredRepoParams) (MonitoredRepo, error) {
	row := q.db.QueryRowContext(ctx, createMonitoredRepo,
		arg.ID,
		arg.SourceKind,
		arg.ProjectPath,
		arg.Enabled,
		arg.SourceIntegrationID,
		arg.TicketProjectID,
		arg.OpenTicketExternalID,
		arg.OpenTicketTag,
		arg.LastKnownTag,
		arg.LastPolledAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MonitoredRepo
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.ProjectPath,
		&i.Enabled,
		&i.SourceIntegrationID,
		&i.TicketProjectID,
		&i.OpenTicketExternalID,
		&i.OpenTicketTag,
		&i.LastKnownTag,
		&i.LastPolledAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitoredRepo = `-- name: DeleteMonitoredRepo :exec
DELETE FROM monitored_repos
WHERE id = ?
`

func (q *Queries) DeleteMonitoredRepo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMonitoredRepo, id)
	return err
}

const getMonitoredRepo = `-- name: GetMonitoredRepo :one
SELECT
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
FROM monitored_repos
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMonitoredRepo(ctx context.Context, id string) (MonitoredRepo, error) {
	row := q.db.QueryRowContext(ctx, getMonitoredRepo, id)
	var i MonitoredRepo
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.ProjectPath,
		&i.Enabled,
		&i.SourceIntegrationID,
		&i.TicketProjectID,
		&i.OpenTicketExternalID,
		&i.OpenTicketTag,
		&i.LastKnownTag,
		&i.LastPolledAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabled = `-- name: ListEnabled :many
SELECT
  mr.id,
  mr.source_kind,
  mr.project_path,
  mr.enabled,
  mr.source_integration_id,
  mr.ticket_project_id,
  mr.open_ticket_external_id,
  mr.open_ticket_tag,
  mr.last_known_tag,
  mr.last_polled_at,
  mr.last_error,
  mr.created_at,
  mr.updated_at,
  COALESCE(GROUP_CONCAT(mrn.notification_target_id), '') AS notification_target_ids
FROM monitored_repos mr
LEFT JOIN monitored_repo_notifications mrn ON mrn.monitored_repo_id = mr.id
WHERE mr.enabled = 1
GROUP BY mr.id
ORDER BY mr.project_path
`

type ListEnabledRow struct {
	ID                    string         `json:"id"`
	SourceKind            string         `json:"source_kind"`
	ProjectPath           string         `json:"project_path"`
	Enabled               int64          `json:"enabled"`
	SourceIntegrationID   sql.NullString `json:"source_integration_id"`
	TicketProjectID       string         `json:"ticket_project_id"`
	OpenTicketExternalID  sql.NullString `json:"open_ticket_external_id"`
	OpenTicketTag         sql.NullString `json:"open_ticket_tag"`
	LastKnownTag          sql.NullString `json:"last_known_tag"`
	LastPolledAt          sql.NullString `json:"last_polled_at"`
	LastError             sql.NullString `json:"last_error"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	NotificationTargetIds interface{}    `json:"notification_target_ids"`
}

func (q *Queries) ListEnabled(ctx context.Context) ([]ListEnabledRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledRow
	for rows.Next() {
		var i ListEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.ProjectPath,
			&i.Enabled,
			&i.SourceIntegrationID,
			&i.TicketProjectID,
			&i.OpenTicketExternalID,
			&i.OpenTicketTag,
			&i.LastKnownTag,
			&i.LastPolledAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationTargetIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoredRepos = `-- name: ListMonitoredRepos :many
SELECT
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
FROM monitored_repos
ORDER BY project_path
`

func (q *Queries) ListMonitoredRepos(ctx context.Context) ([]MonitoredRepo, error) {
	rows, err := q.db.QueryContext(ctx, listMonitoredRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonitoredRepo
	for rows.Next() {
		var i MonitoredRepo
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.ProjectPath,
			&i.Enabled,
			&i.SourceIntegrationID,
			&i.TicketProjectID,
			&i.OpenTicketExternalID,
			&i.OpenTicketTag,
			&i.LastKnownTag,
			&i.LastPolledAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMonitoredRepoEnabled = `-- name: SetMonitoredRepoEnabled :one
UPDATE monitored_repos
SET
  enabled = ?,
  updated_at = ?
WHERE id = ?
RETURNING
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
`

type SetMonitoredRepoEnabledParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetMonitoredRepoEnabled(ctx context.Context, arg SetMonitoredRepoEnabledParams) (MonitoredRepo, error) {
	row := q.db.QueryRowContext(ctx, setMonitoredRepoEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i MonitoredRepo
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.ProjectPath,
		&i.Enabled,
		&i.SourceIntegrationID,
		&i.TicketProjectID,
		&i.OpenTicketExternalID,
		&i.OpenTicketTag,
		&i.LastKnownTag,
		&i.LastPolledAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitoredRepo = `-- name: UpdateMonitoredRepo :one
UPDATE monitored_repos
SET
  source_kind = ?,
  project_path = ?,
  enabled = ?,
  source_integration_id = ?,
  ticket_project_id = ?,
  updated_at = ?
WHERE id = ?
RETURNING
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
`

type UpdateMonitoredRepoParams struct {
	SourceKind          string         `json:"source_kind"`
	ProjectPath         string         `json:"project_path"`
	Enabled             int64          `json:"enabled"`
	SourceIntegrationID sql.NullString `json:"source_integration_id"`
	TicketProjectID     string         `json:"ticket_project_id"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateMonitoredRepo(ctx context.Context, arg UpdateMonitoredRepoParams) (MonitoredRepo, error) {
	row := q.db.QueryRowContext(ctx, updateMonitoredRepo,
		arg.SourceKind,
		arg.ProjectPath,
		arg.Enabled,
		arg.SourceIntegrationID,
		arg.TicketProjectID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i MonitoredRepo
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.ProjectPath,
		&i.Enabled,
		&i.SourceIntegrationID,
		&i.TicketProjectID,
		&i.OpenTicketExternalID,
		&i.OpenTicketTag,
		&i.LastKnownTag,
		&i.LastPolledAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePollState = `-- name: UpdatePollState :one
UPDATE monitored_repos
SET
  open_ticket_external_id = ?,
  open_ticket_tag = ?,
  last_known_tag = ?,
  last_polled_at = ?,
  last_error = ?,
  updated_at = ?
WHERE id = ?
RETURNING
  id,
  source_kind,
  project_path,
  enabled,
  source_integration_id,
  ticket_project_id,
  open_ticket_external_id,
  open_ticket_tag,
  last_known_tag,
  last_polled_at,
  last_error,
  created_at,
  updated_at
`

type UpdatePollStateParams struct {
	OpenTicketExternalID sql.NullString `json:"open_ticket_external_id"`
	OpenTicketTag        sql.NullString `json:"open_ticket_tag"`
	LastKnownTag         sql.NullString `json:"last_known_tag"`
	LastPolledAt         sql.NullString `json:"last_polled_at"`
	LastError            sql.NullString `json:"last_error"`
	UpdatedAt            string         `json:"updated_at"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdatePollState(ctx context.Context, arg UpdatePollStateParams) (MonitoredRepo, error) {
	row := q.db.QueryRowContext(ctx, updatePollState,
		arg.OpenTicketExternalID,
		arg.OpenTicketTag,
		arg.LastKnownTag,
		arg.LastPolledAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	var i MonitoredRepo
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.ProjectPath,
		&i.Enabled,
		&i.SourceIntegrationID,
		&i.TicketProjectID,
		&i.OpenTicketExternalID,
		&i.OpenTicketTag,
		&i.LastKnownTag,
		&i.LastPolledAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
