// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_targets.sql

package db

import (
	"context"
)

const createNotificationTarget = `-- name: CreateNotificationTarget :one
INSERT INTO notification_targets (
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
`

type CreateNotificationTargetParams struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	ShoutrrrUrlEncrypted string `json:"shoutrrr_url_encrypted"`
	EventsJson           string `json:"events_json"`
	Enabled              int64  `json:"enabled"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

func (q *Queries) CreateNotificationTarget(ctx context.Context, arg CreateNotificationTargetParams) (NotificationTarget, error) {
	row := q.db.QueryRowContext(ctx, createNotificationTarget,
		arg.ID,
		arg.Name,
		arg.ShoutrrrUrlEncrypted,
		arg.EventsJson,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i NotificationTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShoutrrrUrlEncrypted,
		&i.EventsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationTarget = `-- name: DeleteNotificationTarget :exec
DELETE FROM notification_targets
WHERE id = ?
`

func (q *Queries) DeleteNotificationTarget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationTarget, id)
	return err
}

const getNotificationTarget = `-- name: GetNotificationTarget :one
SELECT
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
FROM notification_targets
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetNotificationTarget(ctx context.Context, id string) (NotificationTarget, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTarget, id)
	var i NotificationTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShoutrrrUrlEncrypted,
		&i.EventsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledNotificationTargets = `-- name: ListEnabledNotificationTargets :many
SELECT
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
FROM notification_targets
WHERE enabled = 1
ORDER BY name
`

func (q *Queries) ListEnabledNotificationTargets(ctx context.Context) ([]NotificationTarget, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotificationTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTarget
	for rows.Next() {
		var i NotificationTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShoutrrrUrlEncrypted,
			&i.EventsJson,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationTargets = `-- name: ListNotificationTargets :many
SELECT
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
FROM notification_targets
ORDER BY name
`

func (q *Queries) ListNotificationTargets(ctx context.Context) ([]NotificationTarget, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTarget
	for rows.Next() {
		var i NotificationTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShoutrrrUrlEncrypted,
			&i.EventsJson,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationTarget = `-- name: UpdateNotificationTarget :one
UPDATE notification_targets
SET
  name = ?,
  shoutrrr_url_encrypted = ?,
  events_json = ?,
  enabled = ?,
  updated_at = ?
WHERE id = ?
RETURNING
  id,
  name,
  shoutrrr_url_encrypted,
  events_json,
  enabled,
  created_at,
  updated_at
`

type UpdateNotificationTargetParams struct {
	Name                 string `json:"name"`
	ShoutrrrUrlEncrypted string `json:"shoutrrr_url_encrypted"`
	EventsJson           string `json:"events_json"`
	Enabled              int64  `json:"enabled"`
	UpdatedAt            string `json:"updated_at"`
	ID                   string `json:"id"`
}

func (q *Queries) UpdateNotificationTarget(ctx context.Context, arg UpdateNotificationTargetParams) (NotificationTarget, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationTarget,
		arg.Name,
		arg.ShoutrrrUrlEncrypted,
		arg.EventsJson,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i NotificationTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShoutrrrUrlEncrypted,
		&i.EventsJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
