// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poll_runs.sql

package db

import (
	"context"
	"database/sql"
)

const finishRun = `-- name: FinishRun :one
UPDATE poll_runs
SET
  finished_at = ?,
  status = ?,
  repos_checked = ?,
  tickets_created = ?,
  tickets_superseded = ?,
  errors_json = ?
WHERE id = ?
RETURNING
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
`

type FinishRunParams struct {
	FinishedAt        sql.NullString `json:"finished_at"`
	Status            string         `json:"status"`
	ReposChecked      int64          `json:"repos_checked"`
	TicketsCreated    int64          `json:"tickets_created"`
	TicketsSuperseded int64          `json:"tickets_superseded"`
	ErrorsJson        string         `json:"errors_json"`
	ID                string         `json:"id"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, finishRun,
		arg.FinishedAt,
		arg.Status,
		arg.ReposChecked,
		arg.TicketsCreated,
		arg.TicketsSuperseded,
		arg.ErrorsJson,
		arg.ID,
	)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const getPollRun = `-- name: GetPollRun :one
SELECT
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
FROM poll_runs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPollRun(ctx context.Context, id string) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, getPollRun, id)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const incrementPollRunReposChecked = `-- name: IncrementPollRunReposChecked :one
UPDATE poll_runs
SET repos_checked = repos_checked + 1
WHERE id = ?
RETURNING
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
`

func (q *Queries) IncrementPollRunReposChecked(ctx context.Context, id string) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, incrementPollRunReposChecked, id)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const incrementPollRunTicketsCreated = `-- name: IncrementPollRunTicketsCreated :one
UPDATE poll_runs
SET tickets_created = tickets_created + 1
WHERE id = ?
RETURNING
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
`

func (q *Queries) IncrementPollRunTicketsCreated(ctx context.Context, id string) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, incrementPollRunTicketsCreated, id)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const incrementPollRunTicketsSuperseded = `-- name: IncrementPollRunTicketsSuperseded :one
UPDATE poll_runs
SET tickets_superseded = tickets_superseded + 1
WHERE id = ?
RETURNING
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
`

func (q *Queries) IncrementPollRunTicketsSuperseded(ctx context.Context, id string) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, incrementPollRunTicketsSuperseded, id)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO poll_run_events (
  id,
  poll_run_id,
  monitored_repo_id,
  action,
  detail,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING
  id,
  poll_run_id,
  monitored_repo_id,
  action,
  detail,
  created_at
`

type InsertEventParams struct {
	ID              string         `json:"id"`
	PollRunID       string         `json:"poll_run_id"`
	MonitoredRepoID sql.NullString `json:"monitored_repo_id"`
	Action          string         `json:"action"`
	Detail          sql.NullString `json:"detail"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (PollRunEvent, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.ID,
		arg.PollRunID,
		arg.MonitoredRepoID,
		arg.Action,
		arg.Detail,
		arg.CreatedAt,
	)
	var i PollRunEvent
	err := row.Scan(
		&i.ID,
		&i.PollRunID,
		&i.MonitoredRepoID,
		&i.Action,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO poll_runs (
  id,
  started_at,
  status,
  trigger_source
) VALUES (
  ?,
  ?,
  'running',
  ?
)
RETURNING
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
`

type InsertRunParams struct {
	ID            string `json:"id"`
	StartedAt     string `json:"started_at"`
	TriggerSource string `json:"trigger_source"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (PollRun, error) {
	row := q.db.QueryRowContext(ctx, insertRun, arg.ID, arg.StartedAt, arg.TriggerSource)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerSource,
		&i.ReposChecked,
		&i.TicketsCreated,
		&i.TicketsSuperseded,
		&i.ErrorsJson,
	)
	return i, err
}

const listPollRunEventsByRunID = `-- name: ListPollRunEventsByRunID :many
SELECT
  id,
  poll_run_id,
  monitored_repo_id,
  action,
  detail,
  created_at
FROM poll_run_events
WHERE poll_run_id = ?
ORDER BY created_at
`

func (q *Queries) ListPollRunEventsByRunID(ctx context.Context, pollRunID string) ([]PollRunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPollRunEventsByRunID, pollRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollRunEvent
	for rows.Next() {
		var i PollRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.PollRunID,
			&i.MonitoredRepoID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollRuns = `-- name: ListPollRuns :many
SELECT
  id,
  started_at,
  finished_at,
  status,
  trigger_source,
  repos_checked,
  tickets_created,
  tickets_superseded,
  errors_json
FROM poll_runs
ORDER BY started_at DESC
LIMIT ?
OFFSET ?
`

type ListPollRunsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPollRuns(ctx context.Context, arg ListPollRunsParams) ([]PollRun, error) {
	rows, err := q.db.QueryContext(ctx, listPollRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollRun
	for rows.Next() {
		var i PollRun
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.TriggerSource,
			&i.ReposChecked,
			&i.TicketsCreated,
			&i.TicketsSuperseded,
			&i.ErrorsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
