// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const deleteOtherSessionsByUserID = `-- name: DeleteOtherSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = ?
  AND token != ?
`

type DeleteOtherSessionsByUserIDParams struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) DeleteOtherSessionsByUserID(ctx context.Context, arg DeleteOtherSessionsByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessionsByUserID, arg.UserID, arg.Token)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const setSessionUserID = `-- name: SetSessionUserID :exec
UPDATE sessions
SET user_id = ?
WHERE token = ?
`

type SetSessionUserIDParams struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) SetSessionUserID(ctx context.Context, arg SetSessionUserIDParams) error {
	_, err := q.db.ExecContext(ctx, setSessionUserID, arg.UserID, arg.Token)
	return err
}
