// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_projects.sql

package db

import (
	"context"
)

const countMonitoredReposByTicketProject = `-- name: CountMonitoredReposByTicketProject :one
SELECT COUNT(*) AS count
FROM monitored_repos
WHERE ticket_project_id = ?
`

func (q *Queries) CountMonitoredReposByTicketProject(ctx context.Context, ticketProjectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitoredReposByTicketProject, ticketProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicketProject = `-- name: CreateTicketProject :one
INSERT INTO ticket_projects (
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
`

type CreateTicketProjectParams struct {
	ID                 string `json:"id"`
	IntegrationID      string `json:"integration_id"`
	ExternalProjectID  string `json:"external_project_id"`
	Name               string `json:"name"`
	CreateConfig       string `json:"create_config"`
	StatusMapping      string `json:"status_mapping"`
	ContentTemplates   string `json:"content_templates"`
	OnOpenTicketPolicy string `json:"on_open_ticket_policy"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) CreateTicketProject(ctx context.Context, arg CreateTicketProjectParams) (TicketProject, error) {
	row := q.db.QueryRowContext(ctx, createTicketProject,
		arg.ID,
		arg.IntegrationID,
		arg.ExternalProjectID,
		arg.Name,
		arg.CreateConfig,
		arg.StatusMapping,
		arg.ContentTemplates,
		arg.OnOpenTicketPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TicketProject
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalProjectID,
		&i.Name,
		&i.CreateConfig,
		&i.StatusMapping,
		&i.ContentTemplates,
		&i.OnOpenTicketPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicketProject = `-- name: DeleteTicketProject :exec
DELETE FROM ticket_projects
WHERE id = ?
`

func (q *Queries) DeleteTicketProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTicketProject, id)
	return err
}

const getTicketProject = `-- name: GetTicketProject :one
SELECT
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
FROM ticket_projects
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTicketProject(ctx context.Context, id string) (TicketProject, error) {
	row := q.db.QueryRowContext(ctx, getTicketProject, id)
	var i TicketProject
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalProjectID,
		&i.Name,
		&i.CreateConfig,
		&i.StatusMapping,
		&i.ContentTemplates,
		&i.OnOpenTicketPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketProjects = `-- name: ListTicketProjects :many
SELECT
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
FROM ticket_projects
ORDER BY name
`

func (q *Queries) ListTicketProjects(ctx context.Context) ([]TicketProject, error) {
	rows, err := q.db.QueryContext(ctx, listTicketProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketProject
	for rows.Next() {
		var i TicketProject
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.ExternalProjectID,
			&i.Name,
			&i.CreateConfig,
			&i.StatusMapping,
			&i.ContentTemplates,
			&i.OnOpenTicketPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketProjectsByIntegration = `-- name: ListTicketProjectsByIntegration :many
SELECT
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
FROM ticket_projects
WHERE integration_id = ?
ORDER BY name
`

func (q *Queries) ListTicketProjectsByIntegration(ctx context.Context, integrationID string) ([]TicketProject, error) {
	rows, err := q.db.QueryContext(ctx, listTicketProjectsByIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketProject
	for rows.Next() {
		var i TicketProject
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.ExternalProjectID,
			&i.Name,
			&i.CreateConfig,
			&i.StatusMapping,
			&i.ContentTemplates,
			&i.OnOpenTicketPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketProject = `-- name: UpdateTicketProject :one
UPDATE ticket_projects
SET
  name = ?,
  create_config = ?,
  status_mapping = ?,
  content_templates = ?,
  on_open_ticket_policy = ?,
  updated_at = ?
WHERE id = ?
RETURNING
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
`

type UpdateTicketProjectParams struct {
	Name               string `json:"name"`
	CreateConfig       string `json:"create_config"`
	StatusMapping      string `json:"status_mapping"`
	ContentTemplates   string `json:"content_templates"`
	OnOpenTicketPolicy string `json:"on_open_ticket_policy"`
	UpdatedAt          string `json:"updated_at"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateTicketProject(ctx context.Context, arg UpdateTicketProjectParams) (TicketProject, error) {
	row := q.db.QueryRowContext(ctx, updateTicketProject,
		arg.Name,
		arg.CreateConfig,
		arg.StatusMapping,
		arg.ContentTemplates,
		arg.OnOpenTicketPolicy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i TicketProject
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalProjectID,
		&i.Name,
		&i.CreateConfig,
		&i.StatusMapping,
		&i.ContentTemplates,
		&i.OnOpenTicketPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTicketProject = `-- name: UpsertTicketProject :one
INSERT INTO ticket_projects (
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT (integration_id, external_project_id) DO UPDATE SET
  name = excluded.name,
  create_config = excluded.create_config,
  status_mapping = excluded.status_mapping,
  content_templates = excluded.content_templates,
  on_open_ticket_policy = excluded.on_open_ticket_policy,
  updated_at = excluded.updated_at
RETURNING
  id,
  integration_id,
  external_project_id,
  name,
  create_config,
  status_mapping,
  content_templates,
  on_open_ticket_policy,
  created_at,
  updated_at
`

type UpsertTicketProjectParams struct {
	ID                 string `json:"id"`
	IntegrationID      string `json:"integration_id"`
	ExternalProjectID  string `json:"external_project_id"`
	Name               string `json:"name"`
	CreateConfig       string `json:"create_config"`
	StatusMapping      string `json:"status_mapping"`
	ContentTemplates   string `json:"content_templates"`
	OnOpenTicketPolicy string `json:"on_open_ticket_policy"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) UpsertTicketProject(ctx context.Context, arg UpsertTicketProjectParams) (TicketProject, error) {
	row := q.db.QueryRowContext(ctx, upsertTicketProject,
		arg.ID,
		arg.IntegrationID,
		arg.ExternalProjectID,
		arg.Name,
		arg.CreateConfig,
		arg.StatusMapping,
		arg.ContentTemplates,
		arg.OnOpenTicketPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TicketProject
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalProjectID,
		&i.Name,
		&i.CreateConfig,
		&i.StatusMapping,
		&i.ContentTemplates,
		&i.OnOpenTicketPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
