#!/usr/bin/env node
/**
 * Generate golang-migrate SQL from db/schema.sql drift using SQLite sqldiff (free, no Atlas).
 *
 * Usage: node scripts/migrate-diff.mjs <name>
 *   name — snake_case description, e.g. add_foo_column
 *
 * Workflow:
 *   1. current.db  ← apply all migrations/*.up.sql
 *   2. desired.db  ← apply db/schema.sql
 *   3. sqldiff current desired → .up.sql
 *   4. sqldiff desired current → .down.sql
 */
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA = join(root, "db/schema.sql");
const MIGRATIONS = join(root, "migrations");

const name = process.argv[2];
if (!name || !/^[a-z][a-z0-9_]*$/.test(name)) {
  console.error("Usage: node scripts/migrate-diff.mjs <snake_case_name>");
  process.exit(1);
}

for (const bin of ["sqlite3", "sqldiff"]) {
  const check = spawnSync(bin, ["--version"], { encoding: "utf8" });
  if (check.status !== 0) {
    console.error(`migrate-diff requires ${bin} on PATH (SQLite tools)`);
    process.exit(1);
  }
}

if (!existsSync(SCHEMA)) {
  console.error(`Missing ${SCHEMA}`);
  process.exit(1);
}

mkdirSync(MIGRATIONS, { recursive: true });

const tmp = mkdtempSync(join(tmpdir(), "release-ops-migrate-"));
const currentDb = join(tmp, "current.db");
const desiredDb = join(tmp, "desired.db");

function runSqlite(db, sql) {
  const r = spawnSync("sqlite3", [db], { input: sql, encoding: "utf8" });
  if (r.status !== 0) {
    console.error(r.stderr || r.stdout);
    throw new Error(`sqlite3 failed on ${db}`);
  }
}

function applyMigrations(db) {
  runSqlite(db, "PRAGMA foreign_keys=ON;");
  if (!existsSync(MIGRATIONS)) return;
  const ups = readdirSync(MIGRATIONS)
    .filter((f) => f.endsWith(".up.sql"))
    .sort();
  for (const f of ups) {
    runSqlite(db, readFileSync(join(MIGRATIONS, f), "utf8"));
  }
}

function applySchema(db) {
  runSqlite(db, readFileSync(SCHEMA, "utf8"));
}

function sqldiff(from, to) {
  const r = spawnSync("sqldiff", [from, to], { encoding: "utf8" });
  if (r.status !== 0) {
    console.error(r.stderr || r.stdout);
    throw new Error("sqldiff failed");
  }
  return r.stdout.trim();
}

try {
  applyMigrations(currentDb);
  applySchema(desiredDb);

  const upSql = sqldiff(currentDb, desiredDb);
  const downSql = sqldiff(desiredDb, currentDb);

  if (!upSql) {
    console.log("No schema drift — migrations/ already matches db/schema.sql");
    process.exit(0);
  }

  const existing = readdirSync(MIGRATIONS)
    .map((f) => /^(\d{6})_/.exec(f))
    .filter(Boolean)
    .map((m) => Number(m[1]));
  const next = String((existing.length ? Math.max(...existing) : 0) + 1).padStart(6, "0");

  const upPath = join(MIGRATIONS, `${next}_${name}.up.sql`);
  const downPath = join(MIGRATIONS, `${next}_${name}.down.sql`);

  writeFileSync(
    upPath,
    `-- Generated by scripts/migrate-diff.mjs — do not edit by hand\n-- Re-generate: make migrate-diff name=${name}\n\n${upSql}\n`
  );
  writeFileSync(
    downPath,
    `-- Generated by scripts/migrate-diff.mjs — do not edit by hand\n\n${downSql || "-- no-op\n"}\n`
  );

  console.log(`Wrote ${upPath}`);
  console.log(`Wrote ${downPath}`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
