name: PR

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
